package com.twilightimperium.expansioncommand.domain.faction.events;

public enum EventsEnum {
    CONQUERED_FACTION_ADDED,
    CONQUERED_FACTION_LOST,
    CONQUERED_FACTION_PERCENTAGE_UPDATED,
    FACTION_CREATED,
    FACTION_SURRENDER,
    GOVERNMENT_LEVEL_DECREASED,
    GOVERNMENT_LEVEL_INCREASED,
    GOVERNMENT_TYPE_CHANGED,
    TECHNOLOGY_ADDED,
    TECHNOLOGY_LEVEL_INCREASED,
    UNIT_CAPACITY_INCREASED,
    UNIT_COST_DECREASED,
    UNIT_CREATED,
    UNIT_REMOVED
}



